package com.example.tugas_3;


import androidx.appcompat.app.AppCompatActivity;

import android.media.Image;
import android.os.Bundle;
import android.webkit.WebView;
import android.widget.ImageView;
import android.widget.TextView;

public class DetailFilm extends AppCompatActivity {

    private PosterData posterData;

    private ImageView poster;
    private TextView nama, detail;

    private String[] detail_tim = new String[] {"Spider-Man: Homecoming adalah film superhero Amerika 2017 berdasarkan karakter Marvel Comics Spider-Man, diproduksi bersama oleh Columbia Pictures dan Marvel Studios, dan didistribusikan oleh Sony Pictures Releasing. Ini adalah reboot film Spider-Man kedua dan film keenam belas di Marvel Cinematic Universe (MCU). Film ini disutradarai oleh Jon Watts, dari sebuah skenario oleh tim penulis Jonathan Goldstein dan John Francis Daley, Watts dan Christopher Ford, dan Chris McKenna dan Erik Sommers. Tom Holland berperan sebagai Peter Parker / Spider-Man, bersama Michael Keaton, Jon Favreau, Zendaya, Donald Glover, Tyne Daly, Marisa Tomei, dan Robert Downey Jr. Dalam Spider-Man: Homecoming, Peter Parker mencoba menyeimbangkan kehidupan sekolah menengah dengan menjadi Spider-Man saat menghadapi Vulture", "Dunkirk adalah film drama perang sejarah tahun 2017[nb 1] yang disutradarai oleh Christopher Nolan dan diproduseri oleh Emma Thomas dan Christopher Nolan. Naskah ini ditulis oleh Christopher Nolan berdasarkan peristiwa evakuasi Dunkerque di pelabuhan Dunkerque, Prancis, pada tanggal 26 Mei 1940 sampai dengan 4 Juni 1940 semasa Perang Dunia II. Film ini dibintangi oleh Fionn Whitehead, Tom Glynn-Carney, Jack Lowden, Harry Styles, Aneurin Barnard, James D'Arcy, Barry Keoghan, Kenneth Branagh, Cillian Murphy, Mark Rylance dan Tom Hardy.", "Iron Man adalah sebuah film yang berdasarkan tokoh Marvel Comics, Iron Man. Film ini adalah film pertama di Marvel Cinematic Universe. Film ini disutradarai oleh Jon Favreau dan dibintangi Robert Downey Jr., Gwyneth Paltrow, Terrence Howard, dan Jeff Bridges. Film ini dirilis pada 2 Mei 2008 di Amerika Serikat.",
            "Mulan merupakan film laga yang disadur dari legenda China The Ballad of Mulan. Cerita tersebut mengambil latar kehidupan kekaisaran China pada abad kelima. Tokoh utama dari cerita tersebut adalah Mulan, seorang gadis yang menyamar menjadi laki-laki untuk ikut berperang demi menyelamatkan ayahnya, Hua Zhou.","Kisah ini menceritakan seorang ayah bernama Scott Lang (Paul Rudd) yang baru bebas dari tahanan akibat terlibat kasus perncurian. Setelah keluar dari penjara, Scott ditolak oleh anggota keluarganya terutama sang istri, yang ternyata sudah punya gandengan baru.", "Avengers: Endgame adalah film pahlawan super Amerika 2019 yang didasarkan pada tim superhero Avengers dari Marvel Comics, diproduksi oleh Marvel Studios dan didistribusikan oleh Walt Disney Studios Motion Pictures. Ini adalah sekuel The Avengers 2012, film 2015 Avengers: Age of Ultron dan film 2018 Avengers: Infinity War, dan film kedua puluh dua di Marvel Cinematic Universe (MCU). Film ini disutradarai oleh Anthony dan Joe Russo, yang ditulis oleh Christopher Markus dan Stephen McFeely, dan menampilkan pemeran ansambel termasuk Robert Downey Jr, Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, dan Josh Brolin. Dalam film itu, anggota Avengers yang masih hidup dan sekutu mereka berusaha untuk membalikkan kerusakan yang disebabkan oleh Thanos dalam Infinity War.","Bruce Wayne (Ben Affleck) menyelaraskan pasukan dengan Diana Prince (Gal Gadot) dengan rencana untuk merekrut tim metahuman untuk melindungi dunia agar tidak mendekati ancaman proporsi bencana.Ternyata tugas itu tidak mudah, karena setiap rekrutan harus menghadapi setan masa lalu mereka sendiri untuk dapat Bersatu. Akhirnya mereka membentuk liga pahlawan yang belum pernah terjadi sebelumnya. Akhirnya Clark Kent, Bruce dan Diana pun merekrut The Flash (Ezra Miller), Aquaman (Jason Momoa), dan Cyborg (Ray Fisher) dalam tim mereka. Kelima pahlawan super ini harus menghentikan rencana Steppenwolf untuk menggabungkan kekuatan tiga Mother Box (Steppenwolf, DeSaad, dan Darkseid) yang dapat menghancurkan bumi.","Black Widow akan mengisahkan petualangan Natasha sebelum Infinity War yang mana dirinya adalah buronan pemerintah Amerika Serikat (AS) setelah mengkhianati perjanjian Sokovia di Captain America: Civil War. Di film itu, meskipun awalnya bersekutu dengan Iron Man, Natasha berkhianat dengan membantu Captain America dan Winter Soldier lari dari pertempuran di Jerman. Di akhir film, Iron Man menyuruhnya untuk kabur ketimbang harus mendekam di penjara.",
            "Harry, Ron, dan Hermione melanjutkan pencarian mereka untuk menemukan dan menghancurkan tiga Horcrux Voldemort yang tersisa, item magis yang bertanggung jawab atas keabadiannya. Tetapi ketika Relikui Kematian yang mistis terungkap, dan Voldemort mengetahui tentang misi mereka, pertempuran terbesar dimulai, dan kehidupan yang mereka ketahui tidak akan pernah sama lagi.","Kisah Godzilla: King of the Monsters mengambil latar waktu lima tahun setelah keberadaan monster raksasa Titans terungkap. Seorang ahli paleobiologi, dr. Emma Russell (Vera Farmiga), bekerja di sebuah organisasi bernama Monarch yang mengobservasi Titans.","Martin Brody, kepala polisi yang terkenal dengan aksi heroiknya menjaga pantai dari serangan hiu dikisahkan telah meninggal. Ellen kini menjanda, sementara kedua putranya Michael dan Sean telah beranjak dewasa. Mengikuti jejak sang ayah, Sean bekerja sebagai polisi.","Film berkisah tentang sosok Arthur Fleck alias Joker, seorang badut pembawa papan iklan berusia 40 tahun yang diperankan begitu baik oleh aktor berkebangsaan Amerika Serikat, Joaquin Phoenix. Hidup Arthur kacau balau. Ia dikisahkan menderita kelainan otak yang menyebabkan dia tertawa pada waktu yang tidak tepat.","Film yang dirilis pada 2019 ini mengisahkan tentang pertempuran Midway yang terjadi setelah serangan Pearl Harbour. Pada 7 Desember 1941, Jepang menggunakan armada kapal induknya untuk menyerang Pearl Harbour. Serangan Jepang terhadap Pearl Harbour ini merupakan bencana besar bagi Amerika Serikat.","Film Mortal Kombat berkisah tentang seorang ahli bela diri bernama Cole Young (Lewis Tan), yang biasa bertarung untuk mendapatkan uang. Baca juga: 5 Rekomendasi Serial Dokumenter yang Membahas Kasus Kontroversial Seumur hidupnya, Cole Young tak pernah menyadari warisan dan silsilah keluarganya yang tersembunyi. Hingga pada suatu ketika, Kaisar Shang Tsung (Chin Han) dari Outworld mengirim petarung terbaiknya, Sub-Zero (Joe Taslim), untuk memburu Cole. Khawatir akan keselamatan keluarganya, Cole lantas mencari cara untuk melawan kekuatan Outworld.","Film ini sendiri mengisahkan bahwa James Bond (Daniel Craig) yang telah pensiun dari dunia spionase. Dirinya memutuskan untuk hidup tenang sebelum akhirnya kembali terusik lewat kemunculan Felix Leater, teman lama Bond dari CIA yang meminta pertolongan kepadanya.","Dalam kurun waktu imajiner di New Orleans, dalam jaringan kertel narkoba ramai mendistribusikan pil yang disebut \"Power\". Pil ini bisa memberikan kekuatan super bagi penggunanya selama lima menit. Kekuatan yang muncul bervariasi tergantung dari orang yang meminumnya.","Cerita film The Dark Knight bermula saat sekelompok penjahat merampok sebuah bank di Kota Gotham yang menyimpan uang para mafia. Usai tugasnya selesai, para penjahat ini saling membunuh hingga menyisakan Joker yang kemudian kabur dengan uang tersebut.",
            "A Star is Born berkisah tentang Jackson Maine (Bradley Cooper), musisi lagu country yang kariernya tengah meredup. Jackson menderita kecanduan pada alkohol dan obat-obatan terlarang. Saat usai tampil di California, Jackon mampir ke sebuah bar.","Alur cerita. Jauh di jantung daerah kumuh Jakarta berdiri sebuah gedung apartemen telantar yang tak tertembus dan menjadi rumah aman bagi gangster, penjahat dan pembunuh yang paling berbahaya.","The New Mutants berkisah tentang lima mutan muda yang dikarantina di sebuah fasilitas rahasia. Situasi di fasilitas rahasia tersebut berubah ketika seorang mutan bernama Danielle “Dani” Moonstar bergabung ke sana.","Film 21 Bridges mengikuti kisah Andrew Davis (Chadwick Boseman) dalam menangkap para perampok narkoba. Dikisahkan Andrew adalah anak dari seorang perwira polisi. Andrew harus kehilangan ayah yang disayanginya ketika ia gugur saat bertugas menangkap pengedar narkoba."};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_detail_film);

        int posisi = getIntent().getIntExtra("posisi",0);

        posterData = new PosterData();
        poster = findViewById(R.id.detail_poster);
        nama = findViewById(R.id.detail_nama);
        detail = findViewById(R.id.detail_bio);

        poster.setImageResource(posterData.getThumbnail(posisi));
        nama.setText(posterData.getTitle(posisi));
        detail.setText(detail_tim[posisi]);

    }
}